repos:
  -   repo: local
      hooks:
      -   id: gofmt
          name: format go code
          language: system
          entry: gofmt -w
          files: '\.go$'
      -   id: gotest
          name: test go code
          language: system
          entry: go test
          files: '\.go$'
