package response

type Portal struct {
	TwoDSketchStylesGroupQuery     string   `json:"2DSketchStylesGroupQuery"`
	TwoDStylesGroupQuery           string   `json:"2DStylesGroupQuery"`
	ThreeDBasemapGalleryGroupQuery string   `json:"3DBasemapGalleryGroupQuery"`
	Access                         string   `json:"access"`
	AllSSL                         bool     `json:"allSSL"`
	AllowedRedirectURIs            []string `json:"allowedRedirectUris"`
	AnalysisLayersGroupQuery       string   `json:"analysisLayersGroupQuery"`
	AuthorizedCrossOriginDomains   []string `json:"authorizedCrossOriginDomains"`
	AvailableCredits               float32  `json:"availableCredits"`
	BackgroundImage                string   `json:"backgroundImage"`
	BasemapGalleryGroupQuery       string   `json:"basemapGalleryGroupQuery"`
	CanListApps                    bool     `json:"canListApps"`
	CanListConsultingServices      bool     `json:"canListConsultingServices"`
	CanListData                    bool     `json:"canListData"`
	CanListPreProvisionedItems     bool     `json:"canListPreProvisionedItems"`
	CanListSolutions               bool     `json:"canListSolutions"`
	CanProvisionDirectPurchase     bool     `json:"canProvisionDirectPurchase"`
	CanSearchPublic                bool     `json:"canSearchPublic"`
	CanSetCustomBuyLink            bool     `json:"canSetCustomBuyLink"`
	CanSetQuestionnaire            bool     `json:"canSetQuestionnaire"`
	CanShareBingPublic             bool     `json:"canShareBingPublic"`
	CanSharePublic                 bool     `json:"canSharePublic"`
	CanSignInArcGIS                bool     `json:"canSignInArcGIS"`
	CanSignInIDP                   bool     `json:"canSignInIDP"`
	CanSignInOIDC                  bool     `json:"canSignInOIDC"`
	CanSignInSocial                bool     `json:"canSignInSocial"`
	CDNUrl                         string   `json:"cdnUrl"`
	ColorSetsGroupQuery            string   `json:"colorSetsGroupQuery"`
	CommentsEnabled                bool     `json:"commentsEnabled"`
	ContentCategorySetsGroupQuery  string   `json:"contentCategorySetsGroupQuery"`
	Created                        int64    `json:"created"`
	Culture                        string   `json:"culture"`
	CultureFormat                  string   `json:"cultureFormat"`
	CustomBaseUrl                  string   `json:"customBaseUrl"`
	DatabaseQuota                  int      `json:"databaseQuota"`
	DatabaseUsage                  int      `json:"databaseUsage"`
	Default3DBasemapQuery          string   `json:"default3DBasemapQuery"`
	DefaultBasemap                 Basemap  `json:"defaultBasemap"`
	DefaultDevBasemap              Basemap  `json:"defaultDevBasemap"`
	DefaultExtent                  Extent   `json:"defaultExtent"`
	DefaultUserCreditAssignment    int      `json:"defaultUserCreditAssignment"`
	DefaultVectorBasemap           Basemap  `json:"defaultVectorBasemap"`
	Description                    string
	Dev3DBasemapGalleryGroupQuery  string
	DevBasemapGalleryGroupQuery    string
	EueiEnabled                    bool
	FeaturedGroups                 []Group
	FeaturedGroupsId               string         `json:"featuredGroupsId"`
	FeaturedItemsGroupQuery        string         `json:"featuredItemsGroupQuery"`
	FontManifestUrl                string         `json:"fontManifestUrl"`
	G3DTilesGalleryGroupQuery      string         `json:"g3DTilesGalleryGroupQuery"`
	G3dTilesEnabled                bool           `json:"g3dTilesEnabled"`
	GalleryTemplatesGroupQuery     string         `json:"galleryTemplatesGroupQuery"`
	HasCategorySchema              bool           `json:"hasCategorySchema"`
	HasMemberCategorySchema        bool           `json:"hasMemberCategorySchema"`
	HelpBase                       string         `json:"helpBase"`
	HelperServices                 HelperServices `json:"helperServices"`
	HomePageFeaturedContent        string         `json:"homePageFeaturedContent"`
	HomePageFeaturedContentCount   int            `json:"homePageFeaturedContentCount"`
	ID                             string         `json:"id"`
	InactivityTimeout              int            `json:"inactivityTimeout"`
	IsPortal                       bool           `json:"isPortal"`
	IsVerified                     bool           `json:"isVerified"`
	LayerTemplatesGroupQuery       string         `json:"layerTemplatesGroupQuery"`
	LivingAtlasGroupQuery          string         `json:"livingAtlasGroupQuery"`
	MaxTokenExpirationMinutes      int            `json:"maxTokenExpirationMinutes"`
	MetadataEditable               bool           `json:"metadataEditable"`
	MetadataFormats                []string       `json:"metadataFormats"`
	Modified                       int64          `json:"modified"`
	Name                           string         `json:"name"`
	NotificationsEnabled           bool           `json:"notificationsEnabled"`
	PlatformSSO                    bool           `json:"platformSSO"`
	PortalHostname                 string         `json:"portalHostname"`
	PortalMode                     string         `json:"portalMode"`
	PortalName                     string         `json:"portalName"`
	//PortalProperties []PortalProperty `json:"portalProperties"`
	PortalThumbnail                   *string `json:"portalThumbnail"`
	RasterFunctionTemplatesGroupQuery string  `json:"rasterFunctionTemplatesGroupQuery"`
	Region                            string  `json:"region"`
	//RotatorPanels []RotatorPanel `json:"rotatorPanels"`
	ShowHomePageDescription        bool   `json:"showHomePageDescription"`
	StaticImagesUrl                string `json:"staticImagesUrl"`
	StorageQuota                   int    `json:"storageQuota"`
	StorageUsage                   int    `json:"storageUsage"`
	StylesGroupQuery               string `json:"stylesGroupQuery"`
	Supports3DTilesServices        bool   `json:"supports3DTilesServices"`
	SupportsHostedServices         bool   `json:"supportsHostedServices"`
	SymbolSetsGroupQuery           string `json:"symbolSetsGroupQuery"`
	TemplatesGroupQuery            string `json:"templatesGroupQuery"`
	Thumbnail                      string `json:"thumbnail"`
	Units                          string `json:"units"`
	UpdateUserProfileDisabled      bool   `json:"updateUserProfileDisabled"`
	UrlKey                         string `json:"urlKey"`
	Use3dBasemaps                  bool   `json:"use3dBasemaps"`
	UseDefault3dBasemap            bool   `json:"useDefault3dBasemap"`
	UseStandardizedQuery           bool   `json:"useStandardizedQuery"`
	UseVectorBasemaps              bool   `json:"useVectorBasemaps"`
	VectorBasemapGalleryGroupQuery string `json:"vectorBasemapGalleryGroupQuery"`
	//subscriptionInfo SubscriptionInfo `json:"subscriptionInfo"`
	RecycleBinSupported bool     `json:"recycleBinSupported"`
	RecycleBinEnabled   bool     `json:"recycleBinEnabled"`
	IpCntryCode         string   `json:"ipCntryCode"`
	HttpPort            int      `json:"httpPort"`
	HttpsPort           int      `json:"httpsPort"`
	SupportsOAuth       bool     `json:"supportsOAuth"`
	IsReadOnly          bool     `json:"isReadOnly"`
	CurrentVersion      string   `json:"currentVersion"`
	MfaEnabled          bool     `json:"mfaEnabled"`
	Contacts            []string `json:"contacts"`
	User                UserInfo `json:"user"`
	AppInfo             AppInfo  `json:"appInfo"`
}
